---

plugins:
  - jekyll-titles-from-headings

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /:year/:month/:title/
  - scope:
      path: ""
      type: pages
    values:
      layout: default

kramdown:
  parse_block_html: true
  smart_quotes: ["apos", "apos", "quot", "quot"]

titles_from_headings:
  strip_title: true
  collections: true
